[package]
name = "auto-cream-api"
version = "0.1.0"
description = "Automatically set up CreamAPI for Steam games"
authors = ["moosh"]
license = "GPL-3.0"
repository = "https://github.com/MoebiusZero/AutoCreamAPI"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
keyvalues-serde = "0.2"
md5 = "0.7"
winreg = "0.55"
